package DeliveryMan;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.regex.*;

public class Registration extends javax.swing.JFrame {

    private List<DeliveryMan> deliveryManList = new ArrayList<>();

    public Registration() {
        initComponents();
        initializeList();
        jtfName.grabFocus();
        jlblError.setText("");
        jradMale.setActionCommand("M");
        jradFemale.setActionCommand("F");

        int count = 0;
        for (int i = 0; i < deliveryManList.size(); i++) {
            if (deliveryManList.get(i) != null) {
                count++;
            } else {
                break;
            }
        }
        DeliveryMan.setNextId(1000 + count);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgGender = new javax.swing.ButtonGroup();
        jlblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfHomeAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jradMale = new javax.swing.JRadioButton();
        jradFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jbtnClose = new javax.swing.JButton();
        jtfEmail = new javax.swing.JTextField();
        jlblError = new javax.swing.JLabel();
        jbtnRegister = new javax.swing.JButton();
        jtfContactNumber = new javax.swing.JTextField();
        jtfIdentityCardNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jftfBasicSalary = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText("Delivery Man Registration");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name :");

        jtfName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfName.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Gender :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contact Number :");

        jtfHomeAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Home Address :");

        jbgGender.add(jradMale);
        jradMale.setSelected(true);
        jradMale.setText("Male");
        jradMale.setToolTipText("");

        jbgGender.add(jradFemale);
        jradFemale.setText("Female");
        jradFemale.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Email Address :");

        jbtnClose.setBackground(new java.awt.Color(204, 0, 0));
        jbtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jtfEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfEmail.setForeground(java.awt.Color.lightGray);
        jtfEmail.setText("something@someserver.com");
        jtfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEmailFocusLost(evt);
            }
        });

        jlblError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblError.setForeground(java.awt.Color.red);
        jlblError.setText("Error Message");

        jbtnRegister.setBackground(new java.awt.Color(0, 102, 0));
        jbtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegister.setText("Register");
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });

        jtfContactNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfContactNumber.setForeground(java.awt.Color.lightGray);
        jtfContactNumber.setText("01#-########");
        jtfContactNumber.setToolTipText("");
        jtfContactNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfContactNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfContactNumberFocusLost(evt);
            }
        });

        jtfIdentityCardNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfIdentityCardNo.setForeground(java.awt.Color.lightGray);
        jtfIdentityCardNo.setText("######-##-####");
        jtfIdentityCardNo.setToolTipText("");
        jtfIdentityCardNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfIdentityCardNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfIdentityCardNoFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Identity Card No :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Basic Salary(RM) :");

        jftfBasicSalary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfIdentityCardNo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jradMale, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jradFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfContactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jtfHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jlblError, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftfBasicSalary))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIdentityCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradMale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblError)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterActionPerformed
        String name = jtfName.getText().trim();
        String gender = jbgGender.getSelection().getActionCommand().trim();
        String contactNumber = jtfContactNumber.getText().trim();
        String homeAddress = jtfHomeAddress.getText().trim();
        String email = jtfEmail.getText().trim();
        String identityCardNo = jtfIdentityCardNo.getText().trim();
        double basicSalary;

        if (name.isEmpty() || gender.isEmpty() || contactNumber.equals("01#-########")
                || homeAddress.isEmpty() || email.equals("something@someserver.com") || identityCardNo.equals("######-##-####") || jftfBasicSalary.getText().isEmpty()) {
            jlblError.setText("Please fill in all the fields.");
        } else if (!validateIdentityCardNo(identityCardNo)) {
            jlblError.setText("Please enter a valid IC Number.");
            jtfIdentityCardNo.setText("");
            jtfIdentityCardNo.grabFocus();
        } else if (!validateContactNumber(contactNumber)) {
            jlblError.setText("Please enter a valid contact number.");
            jtfContactNumber.setText("");
            jtfContactNumber.grabFocus();
        } else if (!validateEmail(email)) {
            jlblError.setText("Please enter a valid email address.");
            jtfEmail.setText("");
            jtfEmail.grabFocus();
        } else {
            basicSalary = Double.parseDouble(jftfBasicSalary.getText());
            if (basicSalary <= 0) {
                jlblError.setText("Basic Salary must be greater than 0.");
                jftfBasicSalary.setText("");
                jftfBasicSalary.grabFocus();
            } else {
                int option = JOptionPane.showConfirmDialog(null, "Do you want to register this delivery man?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    DeliveryMan deliveryMan = new DeliveryMan(name, gender, contactNumber, email, homeAddress, identityCardNo, basicSalary);
                    deliveryManList.add(deliveryMan);
                    JOptionPane.showMessageDialog(null, "Registered Successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    jtfName.setText("");
                    jtfIdentityCardNo.setText("");
                    jradMale.setSelected(true);
                    jtfContactNumber.setText("");
                    jtfHomeAddress.setText("");
                    jtfEmail.setText("");
                    jftfBasicSalary.setText("");
                    jlblError.setText("");
                    jtfName.grabFocus();

                    String result = String.format("%-4s  %-20s   %-6s    %-12s   %-20s   %-14s   %-12s   %-10s\n", "ID", "NAME", "GENDER", "CONTACT NO.", "EMAIL", "IC NO.", "BASIC_SALARY", "STATUS");
                    for (int i = 0; i < deliveryManList.size(); i++) {
                        if (deliveryManList.get(i) != null) {
                            result += deliveryManList.get(i).toString();
                        } else {
                            break;
                        }
                    }
                    System.out.println("Updated Delivery Man List :");
                    System.out.println(result);
                }
            }
        }
    }//GEN-LAST:event_jbtnRegisterActionPerformed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        try {
            ObjectOutputStream ooStream = new ObjectOutputStream(new FileOutputStream("deliveryMan.dat"));
            ooStream.writeObject(deliveryManList);
            ooStream.close();
            this.dispose();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "File not found", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Cannot save to file", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ObjectOutputStream ooStream = new ObjectOutputStream(new FileOutputStream("deliveryMan.dat"));
            ooStream.writeObject(deliveryManList);
            ooStream.close();
            this.dispose();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "File not found", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Cannot save to file", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jtfContactNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfContactNumberFocusLost
        if (jtfContactNumber.getText().isEmpty()) {
            jtfContactNumber.setForeground(Color.LIGHT_GRAY);
            jtfContactNumber.setText("01#-########");
        }
    }//GEN-LAST:event_jtfContactNumberFocusLost

    private void jtfContactNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfContactNumberFocusGained
        if (jtfContactNumber.getText().equals("01#-########")) {
            jtfContactNumber.setForeground(Color.BLACK);
            jtfContactNumber.setText("");
        }
    }//GEN-LAST:event_jtfContactNumberFocusGained

    private void jtfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusLost
        if (jtfEmail.getText().isEmpty()) {
            jtfEmail.setForeground(Color.LIGHT_GRAY);
            jtfEmail.setText("something@someserver.com");
        }
    }//GEN-LAST:event_jtfEmailFocusLost

    private void jtfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusGained
        if (jtfEmail.getText().equals("something@someserver.com")) {
            jtfEmail.setForeground(Color.BLACK);
            jtfEmail.setText("");
        }
    }//GEN-LAST:event_jtfEmailFocusGained

    private void jtfIdentityCardNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfIdentityCardNoFocusLost
        if (jtfIdentityCardNo.getText().isEmpty()) {
            jtfIdentityCardNo.setForeground(Color.LIGHT_GRAY);
            jtfIdentityCardNo.setText("######-##-####");
        }
    }//GEN-LAST:event_jtfIdentityCardNoFocusLost

    private void jtfIdentityCardNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfIdentityCardNoFocusGained
        if (jtfIdentityCardNo.getText().equals("######-##-####")) {
            jtfIdentityCardNo.setForeground(Color.BLACK);
            jtfIdentityCardNo.setText("");
        }
    }//GEN-LAST:event_jtfIdentityCardNoFocusGained

    private void initializeList() {
        try {
            ObjectInputStream oiStream = new ObjectInputStream(new FileInputStream("deliveryMan.dat"));
            deliveryManList = (ArrayList) (oiStream.readObject());
            oiStream.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "File not found", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Cannot read from file", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Class not found", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validateEmail(String email) {
        String EMAIL_PATTERN = "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$";
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher regrexMatcher = pattern.matcher(email);
        if (regrexMatcher.matches()) {
            return true;
        } else {
            return false;
        }
    }

    private boolean validateContactNumber(String contactNumber) {
        String CONTACTNO_PATTERN = "^01[0-9]{1}-[0-9]{7,8}$";
        Pattern pattern = Pattern.compile(CONTACTNO_PATTERN);
        Matcher regrexMatcher = pattern.matcher(contactNumber);
        if (regrexMatcher.matches()) {
            return true;
        } else {
            return false;
        }
    }

    private boolean validateIdentityCardNo(String identityCardNo) {
        String ICNO_PATTERN = "^[0-9]{6}-[0-9]{2}-[0-9]{4}$";
        Pattern pattern = Pattern.compile(ICNO_PATTERN);
        Matcher regrexMatcher = pattern.matcher(identityCardNo);
        if (regrexMatcher.matches()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.ButtonGroup jbgGender;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JFormattedTextField jftfBasicSalary;
    private javax.swing.JLabel jlblError;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JRadioButton jradFemale;
    private javax.swing.JRadioButton jradMale;
    private javax.swing.JTextField jtfContactNumber;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfHomeAddress;
    private javax.swing.JTextField jtfIdentityCardNo;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
